[project]
name = "uv-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "apache-airflow==2.10.4",
    "pandas==2.2.3",
    "pydantic==2.10.4",
    "scipy==1.14.1",
]
